#!/usr/bin/env php
<?php

/**
 * Declare paths
 */
$basePath = __DIR__;
$dataPath = $basePath . '/kraken-data';

/**
 * Include autoloader & dependencies
 */
require $basePath . '/vendor/autoload.php';
require $dataPath . '/autorun/autorun.php5.polyfill';

if (!defined('STDIN'))
{
    echo("Tried to execute program outside of CLI mode or not enough parameters have been passed.\n");
    exit(1);
}

/**
 * Create console instance
 */
try
{
    $console = (new \Kraken\Console\Client\Boot\ConsoleBoot)
        ->boot(
            $dataPath
        );

    $console
        ->start();
}
catch (\Error $ex)
{
    echo \Kraken\Throwable\Error::toString($ex) . PHP_EOL;
}
catch (\Exception $ex)
{
    echo \Kraken\Throwable\Exception::toString($ex) . PHP_EOL;
}
